import { useEffect, useRef, useState } from 'react';
import { Mail, Phone, MessageCircle, Menu, X, Plus, Minus, Store, Layers3, Handshake, ChartNoAxesCombined, Compass, MapPin, Globe2, BriefcaseBusiness, GraduationCap, Cpu, Workflow, ShoppingBag, Search, Check, Linkedin } from 'lucide-react';
import { profile, metrics, brands, brandAssets, freelance, experiences, capabilities, toolGroups, toolIcons } from './data/portfolio';

const iconSet = [Store, Layers3, Handshake, ChartNoAxesCombined, Compass];
const navItems = [{label:'Impact',id:'impact'}, {label:'Experience',id:'experience'}, {label:'Expertise',id:'expertise'}, {label:'Tools',id:'tools'}];
function Tags({items}: {items:string[]}) { return <div className="tags">{items.map(item=><span key={item}>{item}</span>)}</div> }
function SectionLabel({children, light=false}: {children:React.ReactNode,light?:boolean}) { return <p className={`eyebrow ${light?'light':''}`}><span className="label-line"/>{children}</p> }
function Brand({name}: {name:string}) { const key=name.toLowerCase().replaceAll(' ','-'); const asset=brandAssets[name]; const [failed,setFailed]=useState(false); const src=asset?.src.startsWith('https://')?asset.src:`${import.meta.env.BASE_URL}${asset?.src}`; return <div className={`brand brand-${key} ${asset&&!failed?'has-logo':''}`}>{asset&&!failed?<img src={src} alt={name} width="150" height="56" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<span>{name}</span>}</div> }
function ToolCard({name}: {name:string}) { const slug=toolIcons[name];return <div className="tool-card">{slug?<span className="tool-logo"><img src={`${import.meta.env.BASE_URL}icons/${slug}.svg`} alt="" width="24" height="24" loading="lazy"/></span>:<span className="tool-logo neutral">{/Amazon|Noon|Raya|Raneen/.test(name)?<ShoppingBag size={22}/>: /AI|Chatbots/.test(name)?<Cpu size={22}/>: /SEO|Keyword/.test(name)?<Search size={22}/>: /Power|Excel|Word/.test(name)?<ChartNoAxesCombined size={22}/>:<Workflow size={22}/>}</span>}<span>{name}</span></div> }
function App() {
 const [menuOpen,setMenuOpen]=useState(false);const [activeNav,setActiveNav]=useState('');const [cap,setCap]=useState(0);const [tools,setTools]=useState(0);const [copied,setCopied]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setActiveNav(entry.target.id)}),{rootMargin:'-20% 0px -65% 0px'});navItems.forEach(item=>{const el=document.getElementById(item.id);if(el)observer.observe(el)});return()=>{observer.disconnect();clearTimeout(timer.current)}},[]);
 async function copyEmail(){try{await navigator.clipboard.writeText(profile.email);setCopied(true);clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),2400)}catch{window.location.href=`mailto:${profile.email}`}}
 const CapabilityIcon=iconSet[cap];
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="header"><div className="container nav"><a href="#" className="wordmark" aria-label="Amr Adel, back to top">amr adel<span>.</span></a><nav className={menuOpen?'nav-links open':'nav-links'} aria-label="Main navigation">{navItems.map(item=><a key={item.id} href={`#${item.id}`} className={activeNav===item.id?'active':''} onClick={()=>setMenuOpen(false)}>{item.label}</a>)}<a href="#contact" className="mobile-contact" onClick={()=>setMenuOpen(false)}>Contact</a></nav><a className="button nav-cta" href="#contact">Let’s talk</a><button className="menu-toggle" aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div></header>
 <main id="main">
 <section className="hero container" aria-labelledby="hero-title"><div className="hero-topline"><SectionLabel>E-commerce · Marketplaces · Business Development</SectionLabel><span className="hero-location"><MapPin size={14}/> Egypt, working across markets</span></div><div className="hero-layout"><div className="hero-copy"><p className="hero-intro">Hi, I’m Amr Adel.</p><h1 id="hero-title">E-commerce.<br/>Marketplaces.<br/><span>Growth.</span></h1><p className="hero-description">I connect commercial strategy with hands-on execution to build, grow and optimize digital businesses.</p><p className="hero-experience">5+ years across B2B growth, marketplaces and digital operations.</p><div className="hero-actions"><a className="button primary" href="#contact">Let’s work together</a><a className="text-link" href="#experience">Explore my experience</a></div></div><div className="hero-composition portrait-composition"><div className="portrait-frame"><div className="portrait-topline"><span>AMR ADEL</span><span>COMMERCE LEADERSHIP</span></div><img className="hero-portrait" src={`${import.meta.env.BASE_URL}${profile.portrait}`} alt="Amr Adel, e-commerce and marketplace leader" width="1129" height="1393" fetchPriority="high"/><div className="portrait-metric"><div><p className="portrait-number">$6M<span>+</span></p><h2>Total sales contribution</h2></div><ChartNoAxesCombined size={24}/><p>Cumulative commercial contribution<br/>across my career and brands.</p></div></div><div className="composition-caption"><span>STRATEGY + HANDS-ON EXECUTION</span><span>B2B / B2C</span></div></div></div><div className="hero-bottom"><p>From supplier relationships to the final customer.</p><div><span>E-commerce leadership</span><span>Marketplace growth</span><span>B2B development</span></div></div></section>
 <section id="brands" className="brand-section"><div className="container"><div className="brand-intro"><p>Experience across ambitious businesses<br/>and recognizable retail brands.</p><span>THE BRAND ECOSYSTEM</span></div><div className="brand-grid">{brands.map(name=><Brand key={name} name={name}/>)}</div></div></section>
 <section id="impact" className="impact-section section"><div className="container"><div className="section-heading"><div><SectionLabel>Commercial impact</SectionLabel><h2>Growth measured<br/>in outcomes.</h2></div><p>Commerce is a connected system.<br/>The measure that matters is what it delivers.</p></div><div className="metrics-grid">{metrics.map((metric,i)=><article className={`metric-card metric-${i}`} key={metric.label}><span className="metric-index">0{i+1}</span><p className="metric-value">{metric.value}</p><h3>{metric.label}</h3><p>{metric.detail}</p></article>)}</div><p className="metric-note">Career totals and company contributions are reported separately. Company figures are not an exhaustive allocation of the career total.</p></div></section>
 <section className="positioning container section"><SectionLabel>The way I work</SectionLabel><div className="positioning-grid"><h2>The strategy to see<br/>the opportunity.<br/><span>The execution to<br/>make it happen.</span></h2><div><p className="large-copy">My work sits at the intersection of commerce, operations and business development.</p><p>I bring the marketplace perspective to the storefront, the operational perspective to growth, and the commercial perspective to every partnership.</p><div className="principles"><span><Check size={16}/> Ownership from plan to execution</span><span><Check size={16}/> Collaboration across teams</span><span><Check size={16}/> Problem solving and continuous learning</span></div></div></div></section>
 <section id="experience" className="experience-section section"><div className="container"><div className="section-heading"><div><SectionLabel>Selected experience</SectionLabel><h2>Different businesses.<br/>One growth mindset.</h2></div><p>Building the supply. Growing the channel.<br/>Making the operations work.</p></div>
 <article className="featured featured-souq"><div className="feature-copy"><span className="case-label">01 / B2B MARKETPLACE</span><h3>Souqpress</h3><p className="role">B2B Marketplace Lead &<br/>Business Development Manager</p><p>Growing a B2B marketplace means building both sides of the business. My work connects vendor acquisition and onboarding with customer growth, supplier relationships and commercial partnerships.</p><Tags items={['Business development','Vendor acquisition','Team leadership']}/><details><summary>Explore the scope <Plus size={18}/></summary><div className="detail-content">Marketplace strategy, commercial negotiations, KPI management, market analysis and revenue forecasting, with cross-functional collaboration to turn growth priorities into execution.</div></details></div><div className="feature-proof"><div className="proof-label"><BriefcaseBusiness size={18}/> SOUQPRESS / COMMERCIAL CONTRIBUTION</div><p className="feature-number">$2M<span>+</span></p><p>Business contribution</p><div className="supply-flow"><div><Store size={24}/><span>Suppliers</span></div><span className="flow-line"/><div><Layers3 size={24}/><span>Marketplace</span></div><span className="flow-line"/><div><Handshake size={24}/><span>Customers</span></div></div><p className="proof-caption">Relationships. Supply. Revenue.</p></div></article>
 <article className="featured featured-frg"><div className="feature-copy"><span className="case-label">02 / MULTI-BRAND E-COMMERCE</span><h3>Fashion Retail Group</h3><p className="role">Senior E-commerce Specialist</p><p>Managed marketplace execution for Skechers, ANTA and Umbro. Connected sales performance, product visibility and promotions with purchase orders, stock analysis and platform relationships.</p><Tags items={['Amazon','Noon','Marketplace operations']}/><details><summary>Explore the scope <Plus size={18}/></summary><div className="detail-content">Marketplace reporting, sales analysis, promotional coordination, inventory visibility and e-commerce operations across three established sportswear brands.</div></details></div><div className="feature-proof"><div className="proof-label"><ShoppingBag size={18}/> FASHION RETAIL GROUP / E-COMMERCE</div><p className="feature-number">$2.5M<span>+</span></p><p>E-commerce sales</p><div className="frg-brands">{['Skechers','ANTA','Umbro'].map(name=><Brand key={name} name={name}/>)}</div><p className="proof-caption">Three brands. Connected marketplace execution.</p></div></article>
 <div className="journey-heading"><h3>More experience. Broader perspective.</h3><p>Operations, commercial planning and digital growth.</p></div><div className="career-list">{experiences.map((job,i)=><details className="career-item" key={job.company}><summary><span className="career-index">0{i+3}</span><span className="career-company">{job.company}</span><span className="career-role">{job.role}</span><span className="expand-icon"><Plus className="plus" size={22}/><Minus className="minus" size={22}/></span></summary><div className="career-content"><h4>{job.context}</h4><p>{job.description}</p><Tags items={job.tags}/></div></details>)}</div>
 <article className="bimex-card"><div className="bimex-heading"><span className="bimex-label">BIMEX<span>Part-time</span></span><h3>Business development<br/>for a specialist marketplace.</h3><p>B2B Business Development Manager</p></div><div><p>Supporting the growth of an engineering and BIM marketplace that connects companies and project owners with qualified engineering professionals.</p><p>Client acquisition, lead generation, outbound outreach and pipeline development, with a focus on construction and engineering opportunities in Saudi Arabia and GCC expansion.</p><Tags items={['B2B partnerships','BIM industry','Market development']}/></div></article>
 <div className="freelance-block"><div><SectionLabel>Independent work</SectionLabel><h3>Freelance relationships.</h3><p>Across apparel and home appliances.</p></div><div className="freelance-grid">{freelance.map(name=><div key={name}><span>{name}</span><small>Freelance</small></div>)}</div></div></div></section>
 <section id="expertise" className="expertise-section section container"><div className="section-heading"><div><SectionLabel>Expertise</SectionLabel><h2>Connected capabilities.<br/>Commercial focus.</h2></div><p>A broad view of the business.<br/>A practical understanding of the details.</p></div><div className="capability-system"><div role="tablist" aria-orientation="vertical" aria-label="Expertise areas" className="capability-tabs">{capabilities.map((item,i)=>{const Icon=iconSet[i];return <button role="tab" aria-selected={cap===i} aria-controls="capability-panel" id={`cap-tab-${i}`} tabIndex={cap===i?0:-1} key={item.id} onClick={()=>setCap(i)} onKeyDown={event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const next=(i+(event.key==='ArrowDown'?1:-1)+capabilities.length)%capabilities.length;setCap(next);document.getElementById(`cap-tab-${next}`)?.focus()}}}><Icon size={21}/>{item.title}<span>0{i+1}</span></button>})}</div><div className="capability-panel" role="tabpanel" id="capability-panel" aria-labelledby={`cap-tab-${cap}`}><CapabilityIcon size={36} strokeWidth={1.4}/><h3>{capabilities[cap].headline}</h3><p>{capabilities[cap].description}</p><Tags items={capabilities[cap].skills}/></div></div></section>
 <section className="ecosystem-section section"><div className="container"><div className="ecosystem-top"><SectionLabel light>Commerce ecosystem</SectionLabel><h2>Across platforms.<br/>Across business models.</h2><p>Consumer marketplaces, direct-to-consumer storefronts<br/>and B2B ecosystems — connected by commercial experience.</p></div><div className="ecosystem-map"><div className="eco-row"><span className="eco-category">MARKETPLACES</span><div><b>Amazon</b><b>Noon</b><b>Jumia</b><b>TikTok Marketplace</b></div></div><div className="eco-center"><div className="eco-rule"/><div className="eco-hub"><span>AA</span><p>Commercial strategy<br/><b>+ hands-on execution</b></p></div><div className="eco-rule"/></div><div className="eco-row"><span className="eco-category">STOREFRONTS & B2B</span><div><b>Shopify</b><b>WooCommerce</b><b>B2B marketplaces</b></div></div></div><div className="eco-footer"><Globe2 size={18}/><span>Experience spanning Egypt, Tunisia and Morocco. Business development focused on Saudi Arabia and the GCC.</span></div></div></section>
 <section id="tools" className="tools-section section container"><div className="section-heading"><div><SectionLabel>Technology & tools</SectionLabel><h2>The right tools.<br/>The complete picture.</h2></div><p>From storefront operations to AI automation.<br/>A toolkit built around the work.</p></div><div className="tool-tabs" role="tablist" aria-label="Tool categories">{toolGroups.map((group,i)=><button key={group.title} role="tab" id={`tool-tab-${i}`} aria-controls="tools-panel" aria-selected={tools===i} tabIndex={tools===i?0:-1} onClick={()=>setTools(i)} onKeyDown={event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();const next=(i+(event.key==='ArrowRight'?1:-1)+toolGroups.length)%toolGroups.length;setTools(next);document.getElementById(`tool-tab-${next}`)?.focus()}}}>{group.title}</button>)}</div><div className="tools-panel" role="tabpanel" id="tools-panel" aria-labelledby={`tool-tab-${tools}`}><div className="tool-group-heading"><h3>{toolGroups[tools].summary}</h3><span>{toolGroups[tools].tools.length} tools & platforms</span></div><div className="tools-grid">{toolGroups[tools].tools.map(tool=><ToolCard name={tool} key={tool}/>)}</div></div></section>
 <section className="education-section"><div className="container education-grid"><div><SectionLabel>Always learning</SectionLabel><h2>A commercial mindset.<br/>An engineering foundation.</h2></div><div className="education-list"><article><GraduationCap size={23}/><div><h3>Master of Business Administration</h3><p>Arab Academy for Science and Technology</p><span>2026–2028</span></div></article><article><GraduationCap size={23}/><div><h3>Bachelor of Engineering</h3><p>Mechanical Power Engineering<br/>Banha University / Shubra Faculty of Engineering</p><span>2014–2019</span></div></article><div className="languages"><span><b>English</b> Excellent written & spoken command</span><span><b>German</b> A1</span></div></div></div></section>
 <section id="contact" className="contact-section section"><div className="container"><SectionLabel light>Let’s work together</SectionLabel><div className="contact-top"><h2>Your next chapter<br/>of growth.<br/><span>Let’s build it.</span></h2><div><p>Looking for e-commerce leadership,<br/>marketplace expertise or a commercial partner?</p><a className="button primary" href={`mailto:${profile.email}`}><Mail size={18}/> Email me</a>{profile.linkedin&&<a className="button outline-light" href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={18}/> LinkedIn</a>}<p className="contact-location"><MapPin size={16}/>{profile.location}</p></div></div><div className="contact-grid"><div className="email-card"><span className="contact-label">EMAIL</span><a href={`mailto:${profile.email}`}>{profile.email}</a><button className="copy-button" onClick={copyEmail}>{copied?<Check size={16}/>:<Mail size={16}/>} {copied?'Copied':'Copy email'}</button><span className="sr-only" role="status">{copied?'Email address copied':''}</span></div>{profile.phones.map(phone=><div className="phone-card" key={phone.number}><span className="contact-label">PHONE & WHATSAPP</span><p>{phone.label}</p><div><a href={`tel:${phone.number}`}><Phone size={16}/> Call</a><a href={`https://wa.me/${phone.number.replace('+','')}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> WhatsApp</a></div></div>)}</div><footer><a href="#" className="wordmark">amr adel<span>.</span></a><p>E-commerce. Marketplaces. Growth.</p><span>© {new Date().getFullYear()} Amr Adel</span><a href="#main">Back to top</a></footer></div></section>
 </main></>
}
export default App;
